description=${project.description}
version=${project.version}
name=analysis-bareun
classname=ai.bareun.es.BareunPlugin
java.version=${maven.compiler.target}
elasticsearch.version=${elasticsearch.version}
